#!/usr/bin/bash
# Plot the mixer times generated when cpuCounter is used in audioThread().

CMD="plot"
for FN in "$@"
do
	DAT=/tmp/$(basename $FN).dat
	grep " mix" $FN >$DAT
	CMD+=" '$DAT' using 0:3,"
done

gnuplot -p -e "${CMD%,*}"
